services:
  - type: web
    name: resume-strapi-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 16.14.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
